### ISSUE TITLE
Plugin installation

### ISSUE THREAD

**Issue by al-t** [AckeeCZ/flipper-grpc-plugin#4]
Hello! 
In README.md it's written: 
> You need to install desktop version of the plugin to the Flipper desktop app. Open View > Manage Plugins > Install plugins and search for grpc. Once installed restart the desktop app.

But I wasn't able to find that plugin (I'm using Flipper version 0.146.1 (50.0.0)) - maybe the plugin is not compatible with that version? In fact, all the available plugins are located in the section "Plugin status" and the list in "Install plugins" section is empty.

Also, there is an option to install plugin from tar.gz file, but I don't know where to get it from.

**Comment by Ishmael-ZT** [comment]
install node, install yarn, install flipper-pkg... then run yarn pack
